name: Build & Publish Release APK

on:
  push:
    tags:
      - '*'
jobs:
  Gradle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Release APK
      run: ./gradlew assembleRelease
    - name: Build Android release APK when create new tag
      uses: kyze8439690/action-release-releaseapk@1.0.0
